services:
  api:
    container_name: membros
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # Only use env_file to avoid conflicts
    env_file:
      - backend/.env
    # Additional environment variables that aren't in .env file
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  frontend:
    container_name: membros-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # Build-time variables (NEXT_PUBLIC_* need to be available at build time)
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://api.nohau.agency/api}
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://api.nohau.agency/api}
    depends_on:
      - api
    restart: unless-stopped
