import ClientSideToastContainer from "@/components/client-toast-container";
import { ThemeProvider } from "@/components/theme-provider";
import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            storageKey="colaborador-nohau-theme"
          >
            <ClientSideToastContainer />
            <main className="min-h-screen">{children}</main>
          </ThemeProvider>
        </body>
      </html>
    </>
  );
}
